# Generated by Django 4.0.3 on 2022-04-01 07:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
