# Generated by Django 4.0.3 on 2022-04-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_movies_alter_blog_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
    ]
